# Generated by Django 5.2.4 on 2025-07-07 17:02

import django.db.models.deletion
import food.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
            ],
            options={
                "db_table": "dishes",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
            ],
            options={
                "db_table": "restaurants",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not_started"),
                            ("cooking_rejected", "Cooking_rejected"),
                            ("cooking", "Cooking"),
                            ("cooked", "Cooked"),
                            ("delivery_lookup", "Delivery_lookup"),
                            ("delivery", "Delivery"),
                            ("delivered", "Delivered"),
                            ("not_delivered", "Not_delivered"),
                            ("cancelled_by_customer", "Cancelled_by_customer"),
                            ("cancelled_by_manager", "Cancelled_by_manager"),
                            ("cancelled_by_admin", "Cancelled_by_admin"),
                            ("cancelled_by_restaurant", "Cancelled_by_restaurant"),
                            ("cancelled_by_driver", "Cancelled_by_driver"),
                            ("failed", "Failed"),
                        ],
                        default=food.enums.OrderStatus["NOT_STARTED"],
                        max_length=50,
                    ),
                ),
                ("delivery_provider", models.CharField(max_length=20, null=True)),
                ("eta", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.SmallIntegerField()),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.dish"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.order"
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
            },
        ),
        migrations.AddField(
            model_name="dish",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="food.restaurant"
            ),
        ),
    ]
