# Generated by Django 5.2.4 on 2025-07-07 19:16

import django.db.models.deletion
import food.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="food.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_provider",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("cooking_rejected", "Cooking rejected"),
                    ("cooking", "Cooking"),
                    ("cooked", "Cooked"),
                    ("delivery_lookup", "Delivery lookup"),
                    ("delivery", "Delivery"),
                    ("delivered", "Delivered"),
                    ("not_delivered", "Not delivered"),
                    ("cancelled_by_customer", "Cancelled by customer"),
                    ("cancelled_by_manager", "Cancelled by manager"),
                    ("cancelled_by_admin", "Cancelled by admin"),
                    ("cancelled_by_restaurant", "Cancelled by restaurant"),
                    ("cancelled_by_driver", "Cancelled by driver"),
                    ("failed", "Failed"),
                ],
                default=food.enums.OrderStatus["NOT_STARTED"],
                max_length=50,
            ),
        ),
    ]
