services:
  api:
    build: .
    # entrypoint: ..
    # command: ..
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
      - cache
      - mailing
  database:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis:7
    ports:
      - "6379:6379"
  mailing:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025" # http
      - "8025:8025" # smtp
  silpo_mock:
    build:
      context: .
      dockerfile: Dockerfile
      target: silpo
    container_name: catering-silpo-mock
    ports:
      - "8001:8000"
  kfc_mock:
    build:
      context: .
      dockerfile: Dockerfile
      target: kfc
    container_name: catering-kfc-mock
    ports:
      - "8002:8000"
  uklon_mock:
    build:
      context: .
      dockerfile: Dockerfile
      target: uklon
    container_name: catering-uklon-mock
    ports:
      - "8003:8000"

volumes:
  pgdata: