FROM python:3.13-slim

RUN apt-get update -y \
    # dependencies for building Python packages && clean apt packages
    && apt-get install -y build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set working dir
WORKDIR /app

# Update Project Dependencies
RUN pip install --upgrade pip setuptools pipenv


# Install deps
COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy


# Copy project files
COPY . .


EXPOSE 8000/tcp
ENTRYPOINT [ "python" ]
CMD [ "manage.py", "runserver", "0.0.0.0:8000" ]